name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can adjust the Java version

    - name: Setup Android SDK
      uses: actions/setup-android@v2
      with:
        sdk-version: '30.0.3' # You can adjust the Android SDK version

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build the app
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/debug/*.apk # Adjust the path based on your project structure

    - name: Clean up
      run: ./gradlew clean

